"""init_schema

Revision ID: af4a8ae8f0ab
Revises: 
Create Date: 2026-04-28 06:07:07.071254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af4a8ae8f0ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=1), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('body_scan_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tts_enabled', sa.Boolean(), nullable=False),
    sa.Column('raspberry_pi_ip', sa.String(length=50), nullable=True),
    sa.Column('raspberry_pi_port', sa.Integer(), nullable=True),
    sa.Column('glass_connected', sa.Boolean(), nullable=False),
    sa.Column('glass_device_name', sa.String(length=100), nullable=True),
    sa.Column('notifications_exercise_reminder', sa.Boolean(), nullable=False),
    sa.Column('notifications_weekly_report', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('exercise_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('end_reason', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('set_count', sa.Integer(), nullable=False),
    sa.Column('target_reps_per_set', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_reps_per_set', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rest_sec', sa.Integer(), nullable=False),
    sa.Column('total_reps', sa.Integer(), nullable=False),
    sa.Column('valid_reps', sa.Integer(), nullable=False),
    sa.Column('avg_target_muscle', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('avg_assist_muscle', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('avg_compensator', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('compensation_count', sa.Integer(), nullable=False),
    sa.Column('fatigue_onset_set', sa.Integer(), nullable=True),
    sa.Column('fatigue_onset_rep', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_workout_sessions_exercise_type'), 'workout_sessions', ['exercise_type'], unique=False)
    op.create_index(op.f('ix_workout_sessions_id'), 'workout_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_started_at'), 'workout_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('workout_balance_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('left_value', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('right_value', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('diff_value', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('balance_label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_workout_balance_summaries_id'), 'workout_balance_summaries', ['id'], unique=False)
    op.create_table('workout_calibrations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('ch1_mvc', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('ch2_mvc', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('ch3_mvc', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_calibrations_id'), 'workout_calibrations', ['id'], unique=False)
    op.create_table('workout_muscle_maps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('body_part', sa.String(length=50), nullable=False),
    sa.Column('activation_value', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_muscle_maps_id'), 'workout_muscle_maps', ['id'], unique=False)
    op.create_table('workout_set_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=False),
    sa.Column('actual_reps', sa.Integer(), nullable=False),
    sa.Column('compensation_count', sa.Integer(), nullable=False),
    sa.Column('avg_speed', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_set_results_id'), 'workout_set_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_set_results_id'), table_name='workout_set_results')
    op.drop_table('workout_set_results')
    op.drop_index(op.f('ix_workout_muscle_maps_id'), table_name='workout_muscle_maps')
    op.drop_table('workout_muscle_maps')
    op.drop_index(op.f('ix_workout_calibrations_id'), table_name='workout_calibrations')
    op.drop_table('workout_calibrations')
    op.drop_index(op.f('ix_workout_balance_summaries_id'), table_name='workout_balance_summaries')
    op.drop_table('workout_balance_summaries')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_started_at'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_exercise_type'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
